title: Raph’s blog
author: Raphaël Velt
description: >- # this means to ignore newlines until "baseurl:"
  Reflections about technology, user experience design, and teaching
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://raphv.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: raphv
github_username:  raphv
linkedin_username: raphaelvelt

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Theme settings
minima:
  date_format: "%A %d %B %Y"
