title: Raph’s blog
author: Raphaël Velt
baseurl: "/blog"
url: "https://velt.info"
twitter_username: raphv
github_username:  raphv
linkedin_username: raphaelvelt
show_excerpts: true
excerpt_separator: <!--more-->
permalink: /:year/:month/:title/

header_pages:
 - index.markdown
 - tags/education.md
 - tags/technology.markdown
 - about.markdown

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc

# Theme settings
minima:
  date_format: "%A %d %B %Y"

#Plugin settings
toc:
  min_level: 1
  max_level: 3
  ordered_list: true
